// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuySVb553YzNLAG-0df4ew4egonEvU1qM',
    appId: '1:288534400912:web:96244797d8e9c05a486d15',
    messagingSenderId: '288534400912',
    projectId: 'sahakara-f78dd',
    authDomain: 'sahakara-f78dd.firebaseapp.com',
    storageBucket: 'sahakara-f78dd.firebasestorage.app',
    measurementId: 'G-D7JYEV1LX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3SW95OXflGnhSXMWM4F5AvoLazJpKQpY',
    appId: '1:288534400912:android:1f53ca516397e59a486d15',
    messagingSenderId: '288534400912',
    projectId: 'sahakara-f78dd',
    storageBucket: 'sahakara-f78dd.firebasestorage.app',
  );
}
