name: sahakara
description: "Housemaid management app — owner, maid and admin, one Flutter codebase."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.15.0
  firebase_auth: ^6.7.0
  firebase_data_connect: ^0.3.3
  table_calendar: ^3.3.0
  firebase_storage: ^13.6.0
  image_picker: ^1.2.3
  flutter_tts: ^4.2.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
