export const LANGS = [
  { id: "en", label: "English", short: "EN", speech: "en-US" },
  { id: "si", label: "සිංහල", short: "සි", speech: "si-LK" },
  { id: "ta", label: "தமிழ்", short: "த", speech: "ta-IN" },
];

export const T = {
  appName: { en: "Sathkara", si: "සත්කාර", ta: "சத்காரா" },
  today: { en: "Today", si: "අද", ta: "இன்று" },
  attendance: { en: "Attendance", si: "පැමිණීම", ta: "வருகை" },
  payments: { en: "Payments", si: "ගෙවීම්", ta: "கட்டணம்" },
  settings: { en: "Settings", si: "සැකසුම්", ta: "அமைப்புகள்" },
  myMonth: { en: "My month", si: "මගේ මාසය", ta: "என் மாதம்" },
  owner: { en: "Household", si: "නිවස", ta: "வீடு" },
  helper: { en: "Helper", si: "සහායක", ta: "உதவியாளர்" },
  dayLoad: { en: "Day load", si: "දවසේ බර", ta: "நாள் சுமை" },
  of: { en: "of", si: "න්", ta: "இல்" },
  loadWarn: { en: "This day is nearly full. Adding more will pass the agreed hours.", si: "අද දවස පිරී ඇත. තවත් එකතු කළොත් එකඟ වූ පැය ගණන ඉක්මවයි.", ta: "இந்த நாள் நிரம்பியுள்ளது. மேலும் சேர்த்தால் ஒப்புக்கொண்ட நேரத்தை மீறும்." },
  addTask: { en: "Add task", si: "කාර්යයක් එක් කරන්න", ta: "வேலை சேர்க்க" },
  done: { en: "Done", si: "අවසන්", ta: "முடிந்தது" },
  needHelp: { en: "Can't do", si: "බැහැ", ta: "முடியவில்லை" },
  start: { en: "Start", si: "පටන් ගන්න", ta: "தொடங்கு" },
  listen: { en: "Listen", si: "අහන්න", ta: "கேட்க" },
  high: { en: "High", si: "වැදගත්", ta: "முக்கியம்" },
  normal: { en: "Normal", si: "සාමාන්ය", ta: "சாதாரணம்" },
  low: { en: "Low", si: "අඩු", ta: "குறைவு" },
  mins: { en: "min", si: "මිනිත්තු", ta: "நிமிடம்" },
  daysWorked: { en: "Days worked", si: "වැඩ කළ දින", ta: "வேலை நாட்கள்" },
  stars: { en: "Stars", si: "තරු", ta: "நட்சத்திரங்கள்" },
  tasksDone: { en: "Tasks done", si: "අවසන් කළ කාර්ය", ta: "முடித்த வேலைகள்" },
  giveStar: { en: "Give a star", si: "තරුවක් දෙන්න", ta: "நட்சத்திரம் தர" },
  starred: { en: "Thank you!", si: "ස්තූතියි!", ta: "நன்றி!" },
  present: { en: "Present", si: "පැමිණියා", ta: "வந்தார்" },
  halfDay: { en: "Half day", si: "අඩ දිනය", ta: "அரை நாள்" },
  leave: { en: "Leave", si: "නිවාඩු", ta: "விடுமுறை" },
  holiday: { en: "Holiday", si: "නිවාඩු දිනය", ta: "பொது விடுமுறை" },
  notMarked: { en: "Not marked", si: "සලකුණු කර නැත", ta: "குறிக்கப்படவில்லை" },
  baseSalary: { en: "Base salary", si: "මූලික වැටුප", ta: "அடிப்படை சம்பளம்" },
  overtime: { en: "Overtime", si: "අතිකාල", ta: "கூடுதல் நேரம்" },
  starBonus: { en: "Star bonus", si: "තරු ප්රසාද", ta: "நட்சத்திர ஊக்கத்தொகை" },
  advances: { en: "Advances taken", si: "අත්තිකාරම්", ta: "முன்பணம்" },
  leaveDeduct: { en: "Unpaid leave", si: "නොගෙවන නිවාඩු", ta: "ஊதியமில்லா விடுமுறை" },
  balanceDue: { en: "Balance due", si: "ගෙවිය යුතු ශේෂය", ta: "செலுத்த வேண்டிய தொகை" },
  recordPayment: { en: "Record payment", si: "ගෙවීමක් සටහන් කරන්න", ta: "கட்டணம் பதிவு" },
  addAdvance: { en: "Add advance", si: "අත්තිකාරමක් එක් කරන්න", ta: "முன்பணம் சேர்க்க" },
  history: { en: "Payment history", si: "ගෙවීම් ඉතිහාසය", ta: "கட்டண வரலாறு" },
  flagIssue: { en: "Flag an issue", si: "ගැටලුවක් දන්වන්න", ta: "பிரச்சினை தெரிவிக்க" },
  flagged: { en: "Flagged for the household to check", si: "නිවසට පරීක්ෂා කිරීමට දන්වා ඇත", ta: "வீட்டாருக்குத் தெரிவிக்கப்பட்டது" },
  amount: { en: "Amount", si: "මුදල", ta: "தொகை" },
  note: { en: "Note", si: "සටහන", ta: "குறிப்பு" },
  save: { en: "Save", si: "සුරකින්න", ta: "சேமி" },
  cancel: { en: "Cancel", si: "අවලංගු", ta: "ரத்து" },
  why: { en: "Why not?", si: "ඇයි බැරි?", ta: "ஏன் முடியவில்லை?" },
  pickTask: { en: "Pick a task", si: "කාර්යයක් තෝරන්න", ta: "வேலையைத் தேர்ந்தெடு" },
  priority: { en: "Priority", si: "ප්රමුඛතාව", ta: "முன்னுரிமை" },
  helperName: { en: "Helper's name", si: "සහායකගේ නම", ta: "உதவியாளர் பெயர்" },
  monthlySalary: { en: "Monthly salary (Rs)", si: "මාසික වැටුප (රු)", ta: "மாத சம்பளம் (ரூ)" },
  hoursPerDay: { en: "Agreed hours per day", si: "දිනකට එකඟ වූ පැය", ta: "நாளொன்றுக்கு ஒப்புக்கொண்ட மணி" },
  perStar: { en: "Bonus per star (Rs)", si: "තරුවකට ප්රසාදය (රු)", ta: "ஒரு நட்சத்திரத்திற்கு (ரூ)" },
  language: { en: "Language", si: "භාෂාව", ta: "மொழி" },
  noTasks: { en: "No tasks yet for today. Add the first one.", si: "අද සඳහා කාර්ය නැත. පළමු එක එක් කරන්න.", ta: "இன்று வேலை எதுவும் இல்லை. முதலில் ஒன்றைச் சேர்க்கவும்." },
  noTasksHelper: { en: "Nothing scheduled today. Enjoy the rest.", si: "අද වැඩ නැත. විවේක ගන්න.", ta: "இன்று வேலை இல்லை. ஓய்வெடுங்கள்." },
  carriedOver: { en: "Carried over", si: "පසුදාට ගෙන ආ", ta: "முந்தைய நாளிலிருந்து" },
  viewAs: { en: "Viewing as", si: "බලන්නේ", ta: "பார்வை" },
  earnedSoFar: { en: "Earned so far", si: "මේ දක්වා උපයා ඇත", ta: "இதுவரை சம்பாதித்தது" },
  paidSoFar: { en: "Paid so far", si: "මේ දක්වා ගෙවා ඇත", ta: "இதுவரை பெற்றது" },
  everything: { en: "You can see everything recorded about your work.", si: "ඔබේ වැඩ ගැන සටහන් කර ඇති සියල්ල ඔබට බැලිය හැක.", ta: "உங்கள் வேலை பற்றிய அனைத்துப் பதிவுகளையும் நீங்கள் பார்க்கலாம்." },
};

export const REASONS = [
  { id: "supplies", en: "No supplies", si: "උපකරණ නැත", ta: "பொருட்கள் இல்லை" },
  { id: "water", en: "No water", si: "වතුර නැත", ta: "தண்ணீர் இல்லை" },
  { id: "power", en: "No electricity", si: "විදුලිය නැත", ta: "மின்சாரம் இல்லை" },
  { id: "time", en: "Not enough time", si: "වේලාව මදි", ta: "நேரம் போதவில்லை" },
  { id: "unwell", en: "Feeling unwell", si: "අසනීපයි", ta: "உடல்நலமில்லை" },
];

export const LIBRARY = [
  { id: "t1", mins: 30, en: "Sweep and mop the floors", si: "බිම අතුගා පිස දැමීම", ta: "தரை பெருக்கி துடைத்தல்" },
  { id: "t2", mins: 25, en: "Wash the dishes", si: "පිඟන් සේදීම", ta: "பாத்திரம் கழுவுதல்" },
  { id: "t3", mins: 45, en: "Kitchen deep clean", si: "කුස්සිය හොඳින් පිරිසිදු කිරීම", ta: "சமையலறை ஆழ்ந்த சுத்தம்" },
  { id: "t4", mins: 40, en: "Wash the clothes", si: "රෙදි සේදීම", ta: "துணி துவைத்தல்" },
  { id: "t5", mins: 30, en: "Iron the clothes", si: "රෙදි ඉස්තිරික්ක කිරීම", ta: "துணி அயர்ன் செய்தல்" },
  { id: "t6", mins: 35, en: "Clean the bathrooms", si: "නාන කාමර පිරිසිදු කිරීම", ta: "குளியலறை சுத்தம்" },
  { id: "t7", mins: 20, en: "Dust the furniture", si: "ගෘහ භාණ්ඩ දූවිලි පිසදැමීම", ta: "மரச்சாமான் தூசி துடைத்தல்" },
  { id: "t8", mins: 60, en: "Cook lunch", si: "දිවා ආහාරය පිසීම", ta: "මதிய உணவு சமைத்தல்" },
  { id: "t9", mins: 60, en: "Cook dinner", si: "රාත්රී ආහාරය පිසීම", ta: "இரவு உணவு சமைத்தல்" },
  { id: "t10", mins: 15, en: "Water the garden", si: "උද්යානයට වතුර දැමීම", ta: "தோட்டத்திற்கு நீர் ஊற்றுதல்" },
  { id: "t11", mins: 10, en: "Take out the rubbish", si: "කසළ ඉවත් කිරීම", ta: "குப்பை அகற்றுதல்" },
  { id: "t12", mins: 40, en: "Clean the windows", si: "ජනෙල් පිරිසිදු කිරීම", ta: "ஜன்னல் சுத்தம்" },
  { id: "t13", mins: 30, en: "Clean the fridge", si: "ශීතකරණය පිරිසිදු කිරීම", ta: "குளிர்சாதனப்பெட்டி சுத்தம்" },
  { id: "t14", mins: 15, en: "Change the bed linen", si: "ඇඳ ඇතිරිලි මාරු කිරීම", ta: "படுக்கை விரிப்பு மாற்றுதல்" },
];

export const todayKey = () => new Date().toISOString().slice(0, 10);
export const money = (n) => "Rs " + Math.round(n).toLocaleString("en-LK");
