/// Build/run-time switches, supplied with:
///   flutter run --dart-define-from-file=env.json
///
/// Copy env.example.json to env.json (gitignored). Firebase project config
/// itself lives in firebase_options.dart (generated by `flutterfire configure`).
class Env {
  /// Talk to the local Auth, Data Connect and Storage emulators (`firebase emulators:start`)
  /// instead of the real Firebase project.
  static const useEmulators = bool.fromEnvironment('USE_EMULATORS');
}
